version: '3.8' 

services:
  postgres_db:
    image: postgres:17.2-alpine
    container_name: mini_datamart_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}    
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}      
    ports:
      - "${POSTGRES_PORT: -5432}:5432" # -5432 é default
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  postgres_data: 